name: mlflow-demo-sklearn
channels:
- conda-forge
dependencies:
- python=3.7.10
- pip:
    - pip
    - sklearn==0.0
    - sklearn-pandas==1.8.0
    - mlflow
    - azureml-mlflow
    - tensorflow==2.5.0
    - Keras==2.4.3
    - keras-nightly==2.5.0.dev2021032900
    - Keras-Preprocessing==1.1.2
    - keras-vis==0.4.1
    - matplotlib==3.2.2
    - matplotlib-inline==0.1.2
    - matplotlib-venn==0.11.6